### ISSUE TITLE
Does not track on new time series panel

### ISSUE THREAD

**Issue by N3v3R3nD** [pR0Ps/grafana-trackmap-panel#62] opened 2021-06-11 01:06 UTC
Is it possible to get it to track on the new time series panel?

Grafana 8.0.1

**Comment by nonujigu** [comment] 2021-06-13 09:54
This is a duplicate of #59 .
In Grafana >= 8.0.0 it also does not seem to work with the old Graph panel.

**Comment by pR0Ps** [comment] 2023-01-11 07:30
Fixed by #77 in v2.1.3

**Closed as completed by pR0Ps** 2023-01-11 07:30 UTC
