### ISSUE TITLE
Don't work with new 'Time series' panel

### ISSUE THREAD

**Issue by UlrichThiess** [pR0Ps/grafana-trackmap-panel#59] opened 2021-03-26 14:44 UTC
Tho dot won't shown with the new 'Time series' panel.

**Comment by pR0Ps** [comment] 2021-03-26 14:47
Sounds like a duplicate of #54, if not please reopen with more information.

**Closed by pR0Ps** 2021-03-26 14:47 UTC

**Comment by nonujigu** [comment] 2021-05-30 07:32
I can confirm that TrackMap (version 2.1.2) does not show a blue dot when hovering over the new "Time series" panel which has been [introduced in Grafana 7.4](https://grafana.com/blog/2021/02/10/how-the-new-time-series-panel-brings-major-performance-improvements-and-new-visualization-features-to-grafana-7.4/). I am running Grafana 5.7.7 on a CentOS 7 machine.
If I change the Time series panel to a good old Graph panel, the blue dot is visible as expected when hovering over the Graph panel.
Is it possible that TrackMap currently only supports the hovering function in combination with a Graph Panel?
It should be mentioned that the Time series panel is still in Beta at the time of this post.

**Comment by pR0Ps** [comment] 2023-01-11 07:31
Fixed by #77 in v2.1.3
